/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwartsprojektet;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author EmelieD
 */
public class HanteraKurs extends javax.swing.JFrame {
    
    private final InfDB idb;

    /**
     * Creates new form HanteraKurs
     * @param idb
     */
    public HanteraKurs(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        start = new javax.swing.JPanel();
        kursTaBortKurs = new javax.swing.JButton();
        kursLaggTillKurs = new javax.swing.JButton();
        kursAndra = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        kursBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        laggTillKurs = new javax.swing.JPanel();
        kursnamn = new javax.swing.JTextField();
        larareBox = new javax.swing.JComboBox<>();
        ComboBox.cboxLaggTillLarare(larareBox);
        amne = new javax.swing.JComboBox<>();
        ComboBox.cboxLaggTillAmne(amne);
        kursKursstart = new javax.swing.JTextField();
        kursKursslut = new javax.swing.JTextField();
        kursTillbaka = new javax.swing.JButton();
        laggTill = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        andraKurs = new javax.swing.JPanel();
        andraTillbaka = new javax.swing.JButton();
        kursNamnBox = new javax.swing.JComboBox<>();
        ComboBox.cboxLaggTillKurs(kursNamnBox);
        nyttNamn = new javax.swing.JTextField();
        andraKursstart = new javax.swing.JTextField();
        andraKursslut = new javax.swing.JTextField();
        andraLarare = new javax.swing.JComboBox<>();
        ComboBox.cboxLaggTillLarare(andraLarare);
        andraAmne = new javax.swing.JComboBox<>();
        sparaAndring = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        kursTaBortKurs.setText("Ta bort kurs");
        kursTaBortKurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursTaBortKursActionPerformed(evt);
            }
        });

        kursLaggTillKurs.setText("Lägg till kurs");
        kursLaggTillKurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursLaggTillKursActionPerformed(evt);
            }
        });

        kursAndra.setText("Ändra kurs");
        kursAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursAndraActionPerformed(evt);
            }
        });

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        kursBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dada1", "Dada2", "Charms1", "Herbology 1" }));
        kursBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Kursnamn att ta bort:");

        javax.swing.GroupLayout startLayout = new javax.swing.GroupLayout(start);
        start.setLayout(startLayout);
        startLayout.setHorizontalGroup(
            startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, startLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(startLayout.createSequentialGroup()
                        .addGroup(startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kursLaggTillKurs, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kursAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addGroup(startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startLayout.createSequentialGroup()
                                .addGroup(startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(kursBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kursTaBortKurs, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46))))))
        );
        startLayout.setVerticalGroup(
            startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startLayout.createSequentialGroup()
                .addGroup(startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(kursLaggTillKurs, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(kursBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kursTaBortKurs, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kursAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );

        mainPanel.add(start, "start");

        kursnamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursnamnActionPerformed(evt);
            }
        });

        kursTillbaka.setText("Tillbaka");
        kursTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursTillbakaActionPerformed(evt);
            }
        });

        laggTill.setText("Lägg till kurs");
        laggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laggTillActionPerformed(evt);
            }
        });

        jLabel2.setText("Kursnamn:");

        jLabel3.setText("Lärare:");

        jLabel4.setText("Kursstart:");

        jLabel5.setText("Ämne:");

        jLabel6.setText("Kursslut:");

        javax.swing.GroupLayout laggTillKursLayout = new javax.swing.GroupLayout(laggTillKurs);
        laggTillKurs.setLayout(laggTillKursLayout);
        laggTillKursLayout.setHorizontalGroup(
            laggTillKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laggTillKursLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(kursTillbaka)
                .addGap(128, 128, 128)
                .addComponent(laggTill)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laggTillKursLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(laggTillKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(laggTillKursLayout.createSequentialGroup()
                        .addGroup(laggTillKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(laggTillKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(kursKursstart)
                            .addComponent(larareBox, 0, 83, Short.MAX_VALUE)))
                    .addGroup(laggTillKursLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(kursnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(laggTillKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(laggTillKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amne, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kursKursslut, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        laggTillKursLayout.setVerticalGroup(
            laggTillKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laggTillKursLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(laggTillKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kursnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(laggTillKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(larareBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(39, 39, 39)
                .addGroup(laggTillKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kursKursslut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kursKursstart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(48, 48, 48)
                .addGroup(laggTillKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kursTillbaka)
                    .addComponent(laggTill))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        mainPanel.add(laggTillKurs, "laggTillKurs");

        andraTillbaka.setText("Tillbaka");
        andraTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andraTillbakaActionPerformed(evt);
            }
        });

        andraAmne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Defence Against the Dark Arts", "Charms", "Astronomy", "Flying", "Herbology", "History of Magic", "Potions", "Transfiguration" }));

        sparaAndring.setText("Spara ändring");
        sparaAndring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sparaAndringActionPerformed(evt);
            }
        });

        jLabel7.setText("Kursnamn:");

        jLabel8.setText("Nytt namn:");

        jLabel9.setText("Kursstart:");

        jLabel10.setText("Lärare:");

        jLabel11.setText("Kursslut:");

        jLabel12.setText("Ämne:");

        javax.swing.GroupLayout andraKursLayout = new javax.swing.GroupLayout(andraKurs);
        andraKurs.setLayout(andraKursLayout);
        andraKursLayout.setHorizontalGroup(
            andraKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(andraKursLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(andraKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(andraTillbaka)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGroup(andraKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(andraKursLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(sparaAndring)
                        .addContainerGap())
                    .addGroup(andraKursLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(andraKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(andraLarare, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(andraKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(kursNamnBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE)
                                .addComponent(andraKursstart, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(18, 18, 18)
                        .addGroup(andraKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(andraKursLayout.createSequentialGroup()
                                .addGroup(andraKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(andraKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(andraKursLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(andraKursslut, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, andraKursLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(andraAmne, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(32, Short.MAX_VALUE))
                            .addGroup(andraKursLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(nyttNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        andraKursLayout.setVerticalGroup(
            andraKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, andraKursLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(andraKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kursNamnBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nyttNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(42, 42, 42)
                .addGroup(andraKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(andraKursstart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(andraKursslut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(andraKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(andraLarare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(andraAmne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addGap(37, 37, 37)
                .addGroup(andraKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(andraTillbaka)
                    .addComponent(sparaAndring))
                .addGap(22, 22, 22))
        );

        mainPanel.add(andraKurs, "andraKurs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Stänger ner denna ruta
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    //Tar bort den valda kursen från databasen med hjälp av en SQL fråga
    private void kursTaBortKursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursTaBortKursActionPerformed
        try{
        
            String kursNamn = (String)kursBox.getSelectedItem();
            String andring = "DELETE FROM KURS WHERE KURSNAMN = '" + kursNamn + "'";
            idb.delete(andring);
            JOptionPane.showMessageDialog(null, "Kurs har blivit raderad");
            
        }
            
        catch(InfException e){
            JOptionPane.showMessageDialog(null, "Något gick snett");
                    
        }
    }//GEN-LAST:event_kursTaBortKursActionPerformed

    //Lägger till en kurs med det data som laggts in i fälten med hjälp av SQL frågor
    private void laggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laggTillActionPerformed
        try {
            String kursNamn = kursnamn.getText();
            String lararen = (String) larareBox.getSelectedItem();
            String amnet = (String) amne.getSelectedItem();
            String kursstart = kursKursstart.getText();
            String kursslut = kursKursslut.getText();
            String increment = idb.getAutoIncrement("KURS", "KURS_ID");

            String fragaLarare = "SELECT LARAR_ID FROM LARARE WHERE LARARE.FORNAMN = '" + lararen + "'";
            String lararID = idb.fetchSingle(fragaLarare);

            String fragaAmne = "SELECT AMNE_ID FROM AMNE WHERE AMNESNAMN = '" + amnet + "'";
            String amneID = idb.fetchSingle(fragaAmne);

            String tillagdKurs = "INSERT INTO KURS VALUES ('" + increment + "','" + kursNamn + "','" + kursstart + "','" + kursslut + "','" + lararID + "','" + amneID + "')";
            System.out.println(laggTill);
            idb.insert(tillagdKurs);
            ComboBox.cboxLaggTillAmne(amne);
            ComboBox.cboxLaggTillLarare(larareBox);
            JOptionPane.showMessageDialog(null, "Kurs har blivit tillagd");
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick snett");
        }
    }//GEN-LAST:event_laggTillActionPerformed

    //Byter till rutan start
    private void kursTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursTillbakaActionPerformed
          CardLayout card = (CardLayout)mainPanel.getLayout();
          card.show(mainPanel, "start");
    }//GEN-LAST:event_kursTillbakaActionPerformed

    //Byter till rutan start
    private void andraTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andraTillbakaActionPerformed
         CardLayout card = (CardLayout)mainPanel.getLayout();
         card.show(mainPanel, "start");
    }//GEN-LAST:event_andraTillbakaActionPerformed

    //Byter till rutan laggTillKurs
    private void kursLaggTillKursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursLaggTillKursActionPerformed
          
          CardLayout card = (CardLayout)mainPanel.getLayout();
          card.show(mainPanel, "laggTillKurs");
    }//GEN-LAST:event_kursLaggTillKursActionPerformed
    
    //Byter till rutan andraKurs
    private void kursAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursAndraActionPerformed
          
          CardLayout card = (CardLayout)mainPanel.getLayout();
          card.show(mainPanel, "andraKurs");
    }//GEN-LAST:event_kursAndraActionPerformed

    //Uppdaterar ändringarna som gjorts på kursen med hjälp av datan i fälten och SQL frågor
    private void sparaAndringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sparaAndringActionPerformed
         try {

            String gammalKurs = (String)kursNamnBox.getSelectedItem();
            String nykursNamn = nyttNamn.getText();
            String lararen = (String)andraLarare.getSelectedItem();
            String amnet = (String)andraAmne.getSelectedItem();
            String kursstart = andraKursstart.getText();
            String kursslut = andraKursslut.getText();

            String hamtaID = "SELECT KURS_ID FROM KURS WHERE KURSNAMN = '" + gammalKurs + "'";
            String ID = idb.fetchSingle(hamtaID);

            String fragaLarare = "SELECT LARAR_ID FROM LARARE WHERE LARARE.FORNAMN = '" + lararen + "'";
            String lararID = idb.fetchSingle(fragaLarare);

            String fragaAmne = "SELECT AMNE_ID FROM AMNE WHERE AMNESNAMN = '" + amnet + "'";
            String amneID = idb.fetchSingle(fragaAmne);

            String uppdateraKurs = "UPDATE KURS SET KURS_ID = '" + ID + "', KURSNAMN = '" + nykursNamn + "', KURSSTART = '" + kursstart + "', KURSSLUT = '" + kursslut + "', KURSLARARE = '" + lararID + "', AMNESTILLHORIGHET = '" + amneID + "' WHERE KURSNAMN = '" + gammalKurs + "'";
            idb.update(uppdateraKurs);
            ComboBox.cboxLaggTillLarare(andraLarare);
            ComboBox.cboxLaggTillKurs(kursBox);
            JOptionPane.showMessageDialog(null, "Kurs har blivit ändrad");
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick snett");

        }
    }//GEN-LAST:event_sparaAndringActionPerformed

    private void kursBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kursBoxActionPerformed

    private void kursnamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursnamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kursnamnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> amne;
    private javax.swing.JComboBox<String> andraAmne;
    private javax.swing.JPanel andraKurs;
    private javax.swing.JTextField andraKursslut;
    private javax.swing.JTextField andraKursstart;
    private javax.swing.JComboBox<String> andraLarare;
    private javax.swing.JButton andraTillbaka;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton kursAndra;
    private javax.swing.JComboBox<String> kursBox;
    private javax.swing.JTextField kursKursslut;
    private javax.swing.JTextField kursKursstart;
    private javax.swing.JButton kursLaggTillKurs;
    private javax.swing.JComboBox<String> kursNamnBox;
    private javax.swing.JButton kursTaBortKurs;
    private javax.swing.JButton kursTillbaka;
    private javax.swing.JTextField kursnamn;
    private javax.swing.JButton laggTill;
    private javax.swing.JPanel laggTillKurs;
    private javax.swing.JComboBox<String> larareBox;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nyttNamn;
    private javax.swing.JButton sparaAndring;
    private javax.swing.JPanel start;
    // End of variables declaration//GEN-END:variables
}
