/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwartsprojektet;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author EmelieD
 */
public class KursBetyg extends javax.swing.JFrame {
    
    private final InfDB idb;

    /**
     * Creates new form NewJFrame
     * @param idb
     */
    public KursBetyg(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        betygFornamn = new javax.swing.JTextField();
        betygEfternamn = new javax.swing.JTextField();
        betygBetyg = new javax.swing.JComboBox<>();
        betygTilllbaka = new javax.swing.JButton();
        betygLaggTill = new javax.swing.JButton();
        betygAndra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kursBox = new javax.swing.JComboBox<>();
        ComboBox.cboxLaggTillKurs(kursBox);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        betygBetyg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T", "D", "P", "A", "E", "O" }));
        betygBetyg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betygBetygActionPerformed(evt);
            }
        });

        betygTilllbaka.setText("Tillbaka");
        betygTilllbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betygTilllbakaActionPerformed(evt);
            }
        });

        betygLaggTill.setText("Lägg till");
        betygLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betygLaggTillActionPerformed(evt);
            }
        });

        betygAndra.setText("Ändra");
        betygAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betygAndraActionPerformed(evt);
            }
        });

        jLabel1.setText("Förnamn:");

        jLabel2.setText("Efternamn:");

        jLabel3.setText("Betyg:");

        jLabel4.setText("Kurs:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(betygEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(betygFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(23, 23, 23)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kursBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(betygBetyg, 0, 104, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(betygTilllbaka)
                        .addGap(82, 82, 82)
                        .addComponent(betygLaggTill)
                        .addGap(18, 18, 18)
                        .addComponent(betygAndra)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(betygFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(betygBetyg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(betygEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(kursBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(betygTilllbaka)
                    .addComponent(betygLaggTill)
                    .addComponent(betygAndra))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Lägger till ett betyg i en specifik kurs till den valda eleven med hjälp av comboboxar och SQL frågor
    private void betygLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betygLaggTillActionPerformed
        try {
            String efternamnet = betygEfternamn.getText();
            String fornamnet = betygFornamn.getText();
            String betyget = (String)betygBetyg.getSelectedItem();
            String kurs = (String)kursBox.getSelectedItem();
            String fraga = "SELECT ELEV.ELEV_ID FROM ELEV WHERE ELEV.FORNAMN ='" + fornamnet + "' AND ELEV.EFTERNAMN = '" + efternamnet + "'";
            String elevIdString = idb.fetchSingle(fraga);
            int elevIdInt = Integer.parseInt(elevIdString);

            String kursId = "SELECT KURS.KURS_ID FROM KURS WHERE KURS.KURSNAMN = '" + kurs + "'";
            String kursIdString = idb.fetchSingle(kursId);
            int kursIdInt = Integer.parseInt(kursIdString);
            String laggTillKurs = "INSERT INTO REGISTRERAD_PA VALUES(" + elevIdInt + ", " + kursIdInt + ")";
            idb.insert(laggTillKurs);
            String setBetyg = "INSERT INTO HAR_BETYG_I VALUES(" + elevIdInt + ", " + kursIdInt + ", '" + betyget + "')";
            idb.insert(setBetyg);
            ComboBox.cboxLaggTillKurs(kursBox);
            JOptionPane.showMessageDialog(null, "Betyg har blivit tillagt!");
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick snett");
        }
    }//GEN-LAST:event_betygLaggTillActionPerformed

    //Ändrar betyget i en specifik kurs till den valda eleven med hjälp av comboboxar och SQL frågor
    private void betygAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betygAndraActionPerformed
        try {

            String efternamnet = betygEfternamn.getText();
            String fornamnet = betygFornamn.getText();
            String betyget = (String)betygBetyg.getSelectedItem();
            String kurs = (String)kursBox.getSelectedItem();
            String fraga = "SELECT ELEV.ELEV_ID FROM ELEV WHERE ELEV.FORNAMN ='" + fornamnet + "' AND ELEV.EFTERNAMN = '" + efternamnet + "'";
            String elevIdString = idb.fetchSingle(fraga);
            int elevIdInt = Integer.parseInt(elevIdString);

            String kursId = "SELECT KURS.KURS_ID FROM KURS WHERE KURS.KURSNAMN = '" + kurs + "'";
            String kursIdString = idb.fetchSingle(kursId);
            int kursIdInt = Integer.parseInt(kursIdString);

            String andrabetyget = "UPDATE HAR_BETYG_I SET HAR_BETYG_I.KURSBETYG ='" + betyget + "' WHERE ELEV_ID = " + elevIdInt + "AND KURS_ID = " + kursIdInt + ";";
            idb.update(andrabetyget);
            ComboBox.cboxLaggTillKurs(kursBox);
            JOptionPane.showMessageDialog(null, "Betyg har blivit ändrat");

        } catch (InfException e) {

            JOptionPane.showMessageDialog(null, "Något gick snett");

        }
    }//GEN-LAST:event_betygAndraActionPerformed

    //Stänger denna ruta
    private void betygTilllbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betygTilllbakaActionPerformed
     
        this.dispose();
    }//GEN-LAST:event_betygTilllbakaActionPerformed

    private void betygBetygActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betygBetygActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_betygBetygActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton betygAndra;
    private javax.swing.JComboBox<String> betygBetyg;
    private javax.swing.JTextField betygEfternamn;
    private javax.swing.JTextField betygFornamn;
    private javax.swing.JButton betygLaggTill;
    private javax.swing.JButton betygTilllbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> kursBox;
    // End of variables declaration//GEN-END:variables
}
