/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwartsprojektet;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;





/**
 *
 * @author EmelieD
 */
public class LarareKurs extends javax.swing.JFrame {
    private final InfDB idb;

    /**
     * Creates new form LarareKurs
     * @param idb;
     */
    public LarareKurs(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resultat = new javax.swing.JTextArea();
        startDatum = new javax.swing.JTextField();
        slutDatum = new javax.swing.JTextField();
        larareBox = new javax.swing.JComboBox<>();
        ComboBox.cboxLaggTillLarare(larareBox);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        visa = new javax.swing.JButton();
        larareKursTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultat.setColumns(20);
        resultat.setRows(5);
        jScrollPane1.setViewportView(resultat);

        jLabel1.setText("Startdatum:");

        jLabel2.setText("Slutdatum:");

        jLabel3.setText("Lärare:");

        visa.setText("Visa");
        visa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaActionPerformed(evt);
            }
        });

        larareKursTillbaka.setText("Tillbaka");
        larareKursTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                larareKursTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(startDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(slutDatum)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(larareKursTillbaka)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(visa)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(jLabel3))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(larareBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slutDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(larareBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(visa)
                            .addComponent(larareKursTillbaka))
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaActionPerformed
        if (Validering.omRutaTom(startDatum) && Validering.omRutaTom(slutDatum)) {
            try {
                String kursstart = startDatum.getText();
                String kursslut = slutDatum.getText();
                String lararnamn = (String) larareBox.getSelectedItem();

                String fragan = "SELECT KURS.KURSNAMN FROM KURS JOIN LARARE ON LARARE.LARAR_ID = KURS.KURSLARARE WHERE LARARE.FORNAMN ='" + lararnamn + "'AND KURS.KURSSTART >= '" + kursstart + "' AND KURS.KURSSLUT <= '" + kursslut + "'";
                System.out.println(fragan);
                ArrayList<String> kursNamn = idb.fetchColumn(fragan);

                fragan = "SELECT KURS.KURSNAMN FROM KURS JOIN LARARE ON LARARE.LARAR_ID = KURS.KURSLARARE WHERE LARARE.FORNAMN ='" + lararnamn + "'AND KURS.KURSSTART >= '" + kursstart + "' AND KURS.KURSSLUT <= '" + kursslut + "'";
                System.out.println(fragan);
                ArrayList<String> slut = idb.fetchColumn(fragan);

                fragan = "SELECT KURS.KURSNAMN FROM KURS JOIN LARARE ON LARARE.LARAR_ID = KURS.KURSLARARE WHERE LARARE.FORNAMN ='" + lararnamn + "'AND KURS.KURSSTART >= '" + kursstart + "' AND KURS.KURSSLUT <= '" + kursslut + "'";
                System.out.println(fragan);
                ArrayList<String> start = idb.fetchColumn(fragan);

                String svaret = " ";
                try {
                    for (int i = 0; i < start.size(); i++) {
                        svaret += kursNamn.get(i) + "\n";

                    }
                } catch (NullPointerException e) {
                    System.out.println("Tom loop");
                    JOptionPane.showMessageDialog(null, "Något gick snett");
                }

                resultat.setText(svaret);
            } catch (InfException e) {

                JOptionPane.showMessageDialog(null, "Något gick snett");
                System.out.println("Internt fel meddelande" + e.getMessage());
            }
        }
    }//GEN-LAST:event_visaActionPerformed

    private void larareKursTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_larareKursTillbakaActionPerformed
        
        new Elev(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_larareKursTillbakaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> larareBox;
    private javax.swing.JButton larareKursTillbaka;
    private javax.swing.JTextArea resultat;
    private javax.swing.JTextField slutDatum;
    private javax.swing.JTextField startDatum;
    private javax.swing.JButton visa;
    // End of variables declaration//GEN-END:variables
}
