/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwartsprojektet;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author EmelieD
 */
public class PrefektForestandare extends javax.swing.JFrame {
    
    private final InfDB idb;

    /**
     * Creates new form PrefektForestandare
     * @param idb
     */
    public PrefektForestandare(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prefektFornamn = new javax.swing.JTextField();
        prefektEfternamn = new javax.swing.JTextField();
        prefektElevhem = new javax.swing.JComboBox<>();
        prefektAndring = new javax.swing.JButton();
        prefektTillbaka = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        prefektForestandare = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        prefektElevhem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gryffindor", "Slytherin", "Ravenclaw", "Hufflepuff" }));

        prefektAndring.setText("Ändra prefekt");
        prefektAndring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefektAndringActionPerformed(evt);
            }
        });

        prefektTillbaka.setText("Tillbaka");
        prefektTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefektTillbakaActionPerformed(evt);
            }
        });

        jLabel1.setText("Förnamn:");

        jLabel2.setText("Efternamn:");

        jLabel3.setText("Elevhem:");

        prefektForestandare.setText("Ändra förståndare");
        prefektForestandare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefektForestandareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prefektFornamn)
                    .addComponent(prefektEfternamn)
                    .addComponent(prefektElevhem, 0, 119, Short.MAX_VALUE))
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(prefektTillbaka)
                .addGap(26, 26, 26)
                .addComponent(prefektAndring)
                .addGap(18, 18, 18)
                .addComponent(prefektForestandare)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prefektFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addComponent(prefektEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefektElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prefektAndring)
                            .addComponent(prefektForestandare))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prefektTillbaka)
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Ändrar prefekt med hjälp av data som skrivits in i fälten och SQL frågor
    private void prefektAndringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefektAndringActionPerformed
    if(Validering.omRutaTom(prefektFornamn) && Validering.omRutaTom(prefektEfternamn)){      
        try {
            String fornamnet = prefektFornamn.getText();
            String efternamnet = prefektEfternamn.getText();
            String elevhemmet = (String) prefektElevhem.getSelectedItem();

            String elevID = "SELECT ELEV_ID FROM ELEV WHERE FORNAMN = '" + fornamnet + "' AND EFTERNAMN = '" + efternamnet + "'";
            String ID = idb.fetchSingle(elevID);

            String andring = "UPDATE ELEVHEM SET PREFEKT = '" + ID + "' WHERE ELEVHEMSNAMN = '" + elevhemmet + "'";
            idb.update(andring);
            JOptionPane.showMessageDialog(null, "Prefekt har blivit uppdaterad");
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick snett");

        }
    }
    }//GEN-LAST:event_prefektAndringActionPerformed

    //Ändrar föreståndare med hjälp av data som skrivits in i fälten och SQL frågor
    private void prefektForestandareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefektForestandareActionPerformed
     if(Validering.omRutaTom(prefektFornamn) && Validering.omRutaTom(prefektEfternamn)){     
        try {
            String fornamnet = prefektFornamn.getText();
            String efternamnet = prefektEfternamn.getText();
            String elevhemmet = (String) prefektElevhem.getSelectedItem();

            String lararID = "SELECT LARAR_ID FROM LARARE WHERE FORNAMN = '" + fornamnet + "' AND EFTERNAMN = '" + efternamnet + "'";
            String ID = idb.fetchSingle(lararID);

            String andring = "UPDATE ELEVHEM SET FORESTANDARE = '" + ID + "' WHERE ELEVHEMSNAMN = '" + elevhemmet + "'";
            idb.update(andring);
            JOptionPane.showMessageDialog(null, "Föreståndare har blivit uppdaterad");
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick snett");

        }
     }
    }//GEN-LAST:event_prefektForestandareActionPerformed

    //Stänger denna ruta
    private void prefektTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefektTillbakaActionPerformed
     
        this.dispose();
    }//GEN-LAST:event_prefektTillbakaActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton prefektAndring;
    private javax.swing.JTextField prefektEfternamn;
    private javax.swing.JComboBox<String> prefektElevhem;
    private javax.swing.JButton prefektForestandare;
    private javax.swing.JTextField prefektFornamn;
    private javax.swing.JButton prefektTillbaka;
    // End of variables declaration//GEN-END:variables
}
